### ISSUE TITLE
LSH implementation seems bugged

### ISSUE THREAD

**Issue by tornikeo** [roman-bushuiev/DreaMS_legacy#2]
Specifically, [this line](https://github.com/roman-bushuiev/DreaMS/blob/837bda9ddf7a1b9c4f474a995eb9613373d9cac3/dreams/algorithms/lsh/lsh.py#L18):

```py
            proj_signs = proj_signs.dot(1 << np.arange(proj_signs.shape[-1] - 1, -1, -1))
```

seems to result in a dot product with a mostly zero-filled array. In my local experiments, the

```
print((1 << np.arange(65, -1, -1)))
```

 results in:

```
array([                   0,                    0, -9223372036854775808,
        4611686018427387904,  2305843009213693952,  1152921504606846976, ...
                        256,                  128,                   64,
                         32,                   16,                    8,
                          4,                    2,                    1])
```

So, it seems that `proj_signs`, which should have a shape of `N, n_hyperplane`, gets dotted to a mostly zero-filled vector of shape `n_hyperplane`, so seemingly most of the projected planes (outside of last 64), never get a chance to influence the score at all. The 1000 dimensions (default) plane seems to be equivalent to 64-dimention one?

**Comment by tornikeo** [comment]
I belive this code should be changed with something like this (working on PR, right now):

```
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(42)
boolean_array = np.random.choice([True, False], size=(1000, 1024))
boolean_array = np.ascontiguousarray(boolean_array.astype(np.uint8))
print(boolean_array, boolean_array.shape, boolean_array.dtype)
integer_array = np.packbits(boolean_array, axis=1)
print(integer_array, integer_array.shape, integer_array.dtype)
integer_array = np.bitwise_xor.reduce(integer_array, axis=1)
plt.hist(integer_array)
```

This results in:

```
[[1 0 1 ... 1 0 0]
 [0 0 0 ... 0 0 1]
 [1 1 0 ... 0 1 0]
 ...
 [0 1 0 ... 1 0 1]
 [1 1 0 ... 1 1 0]
 [0 0 1 ... 1 0 1]] (1000, 1024) uint8
[[187 189  20 ... 125  54  92]
 [ 30 167 183 ... 163 165 241]
 [211  90 151 ... 147 160  50]
 ...
 [ 81 189 209 ... 169 200 213]
 [194 153 231 ... 170 252 166]
 [ 58 129  51 ... 218 152  69]] (1000, 128) uint8
```
While for sanity checking, the histogram seems to look like a uniform distribution, although, this likely needs a larger number of bins

![image](https://github.com/roman-bushuiev/DreaMS/assets/56438982/9d908661-6519-4507-ab55-86e65fb5b30b)

**Comment by roman-bushuiev** [comment]
Hi Tornike!

Thank you very much for looking into this! You are right, there is a bug and the default implementation uses up to 64 hyperplanes. This should not be a problem for the overall approach since 60 hyperplanes seem to be sufficient for detecting near-duplicate spectra without resulting in false-positive detections, as shown in the figure from [this notebook](https://github.com/pluskal-lab/DreaMS/blob/main/experiments/lsh_estimations/lsh_gems.ipynb). However, it explains why I didn't see any improvement with the larger number of hyperplanes.

<img width="413" alt="image" src="https://github.com/roman-bushuiev/DreaMS/assets/37666912/bc26a5e8-7620-4648-b865-9ecce26efa00">

I am very sorry for the inconvenience, but could you please replicate the pull request (and issue) in the [new DreaMS repository](https://github.com/pluskal-lab/DreaMS) (belonging to the pluskal-lab profile, not my profile)? I will merge it!

Thanks a lot again!!

**Comment by tornikeo** [comment]
No problem, thanks for letting me know. Will make another PR there. I'll close this PR in a bit.

Also, a quick question:  Do you know how to access the NIST20 dataset referenced in this paper? The dataset seems to be not available online at all.

**Comment by roman-bushuiev** [comment]
Thank you. Unfortunately, NIST20 requires a license to be used, so I didn't use it, for example, for the contrastive learning model used to generate DreaMS embeddings. So, I used GeMS for pre-training and a subset of MoNA for fine-tuning. Moreover, the newest version NIST23 does not allow the export of spectra for machine learning even with a license. I think I will try to completely avoid using NIST data in the future.

Feel free to write to me if you have any other questions!

**Comment by tornikeo** [comment]
Aha. Then I won't waste any more time with NIST. Thanks again!
